# 默认配置模板
app:
  name: AgentCatAgent
  env: dev
  log_level: info

docker:
  endpoint: unix:///var/run/docker.sock
  timeout: 10s

llm:
  provider: openai
  api_key: ""
  model: gpt-4

notifier:
  channel: console 